INSERT INTO book_interests.genre (genre) VALUES
	 ('fiction'),
	 ('nonfiction'),
	 ('biography'),
	 ('journal'),
	 ('travel'),
	 ('spirituality'),
	 ('romance'),
	 ('adventure'),
	 ('classic'),
	 ('coming of age');
INSERT INTO book_interests.genre (genre) VALUES
	 ('fantasy'),
	 ('self help'),
	 ('poetry'),
	 ('philosophy'),
	 ('fiction'),
	 ('nonfiction'),
	 ('biography'),
	 ('journal'),
	 ('travel'),
	 ('spirituality');
INSERT INTO book_interests.genre (genre) VALUES
	 ('romance'),
	 ('adventure'),
	 ('classic'),
	 ('coming of age'),
	 ('fantasy'),
	 ('self help'),
	 ('poetry'),
	 ('philosophy'),
	 ('fiction'),
	 ('nonfiction');
INSERT INTO book_interests.genre (genre) VALUES
	 ('biography'),
	 ('journal'),
	 ('travel'),
	 ('spirituality'),
	 ('romance'),
	 ('adventure'),
	 ('classic'),
	 ('coming of age'),
	 ('fantasy'),
	 ('self help');
INSERT INTO book_interests.genre (genre) VALUES
	 ('poetry'),
	 ('philosophy'),
	 ('fiction'),
	 ('nonfiction'),
	 ('biography'),
	 ('journal'),
	 ('travel'),
	 ('spirituality'),
	 ('romance'),
	 ('adventure');
INSERT INTO book_interests.genre (genre) VALUES
	 ('classic'),
	 ('coming of age'),
	 ('fantasy'),
	 ('self help'),
	 ('poetry'),
	 ('philosophy'),
	 ('fiction'),
	 ('nonfiction'),
	 ('biography'),
	 ('journal');
INSERT INTO book_interests.genre (genre) VALUES
	 ('travel'),
	 ('spirituality'),
	 ('romance'),
	 ('adventure'),
	 ('classic'),
	 ('coming of age'),
	 ('fantasy'),
	 ('self help'),
	 ('poetry'),
	 ('philosophy');
INSERT INTO book_interests.genre (genre) VALUES
	 ('fiction'),
	 ('nonfiction'),
	 ('biography'),
	 ('journal'),
	 ('travel'),
	 ('spirituality'),
	 ('romance'),
	 ('adventure'),
	 ('classic'),
	 ('coming of age');
INSERT INTO book_interests.genre (genre) VALUES
	 ('fantasy'),
	 ('self help'),
	 ('poetry'),
	 ('philosophy'),
	 ('fiction'),
	 ('nonfiction'),
	 ('biography'),
	 ('journal'),
	 ('travel'),
	 ('spirituality');
INSERT INTO book_interests.genre (genre) VALUES
	 ('romance'),
	 ('adventure'),
	 ('classic'),
	 ('coming of age'),
	 ('fantasy'),
	 ('self help'),
	 ('poetry'),
	 ('philosophy'),
	 ('fiction'),
	 ('nonfiction');
INSERT INTO book_interests.genre (genre) VALUES
	 ('biography'),
	 ('journal'),
	 ('travel'),
	 ('spirituality'),
	 ('romance'),
	 ('adventure'),
	 ('classic'),
	 ('coming of age'),
	 ('fantasy'),
	 ('self help');
INSERT INTO book_interests.genre (genre) VALUES
	 ('poetry'),
	 ('philosophy'),
	 ('thriller'),
	 ('crime'),
	 ('fiction'),
	 ('nonfiction'),
	 ('biography'),
	 ('journal'),
	 ('travel'),
	 ('spirituality');
INSERT INTO book_interests.genre (genre) VALUES
	 ('romance'),
	 ('adventure'),
	 ('classic'),
	 ('coming of age'),
	 ('fantasy'),
	 ('self help'),
	 ('poetry'),
	 ('philosophy'),
	 ('thriller'),
	 ('crime');
INSERT INTO book_interests.genre (genre) VALUES
	 ('fiction'),
	 ('nonfiction'),
	 ('biography'),
	 ('journal'),
	 ('travel'),
	 ('spirituality'),
	 ('romance'),
	 ('adventure'),
	 ('classic'),
	 ('coming of age');
INSERT INTO book_interests.genre (genre) VALUES
	 ('fantasy'),
	 ('self help'),
	 ('poetry'),
	 ('philosophy'),
	 ('thriller'),
	 ('crime');
